In [7]:
import numpy as np

# 1 D Numpy Array using Tuple and list

In [10]:
arr = np.array((1,2,3,4,5))
print(arr)
arr.shape

[1 2 3 4 5]


(5,)

In [12]:
arr = np.array([10,11,12,13,12,15])
print(arr)
arr.shape

[10 11 12 13 12 15]


(6,)

## 2 D Numpy Array using Tuple and list

In [18]:
nums = np.array(((1,3,5),(2,5,6),(3,6,8),(1,3,5)))
print(nums)
nums.shape

[[1 3 5]
 [2 5 6]
 [3 6 8]
 [1 3 5]]


(4, 3)

In [19]:
nums = np.array([[5,6,7],[9,5,10],[15,70,45]])
print(nums)
nums.shape

[[ 5  6  7]
 [ 9  5 10]
 [15 70 45]]


(3, 3)

## 3 D Numpy Array using Tuple and List


In [29]:
arr = np.array((((1,2,3),(5,6,7),(7,8,9)),((8,9,10),(1,2,5),(4,7,5))))
print(arr)
arr.shape

[[[ 1  2  3]
  [ 5  6  7]
  [ 7  8  9]]

 [[ 8  9 10]
  [ 1  2  5]
  [ 4  7  5]]]


(2, 3, 3)

In [30]:
arr = np.array([[[1,2,5],[6,8,10]],[[4,5,6],[9,5,3]]])
print(arr)
arr.shape

[[[ 1  2  5]
  [ 6  8 10]]

 [[ 4  5  6]
  [ 9  5  3]]]


(2, 2, 3)

# Access 2-D Arrays

In [33]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])
arr.shape

2


(2, 5)

# Access 3-D Arrays

In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,2])
arr.shape

12


(2, 2, 3)

# Slicing Array

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[:4])
print(arr[4:])
print(arr[-3:-1])


[2 3 4 5]
[1 2 3 4]
[5 6 7]
[5 6]


# Step in Array Slicing

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


# Slicing 2-D Arrays

In [50]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[::, 2])
print(arr[::, 1:4])


[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
